### ISSUE TITLE
Wow, this rules! One request. Need one more dot.

### ISSUE THREAD

**Issue by ddow** [eieste/VersionParserJS#1]
I run into a lot of stuff like this:

`Version: 2.7.2.127; QuickTime 7798000; .NET CLR 2.0.50727.4927;.NET CLR 3.0.30729.4926;.NET CLR 3.5.30729.4926;; Microsoft Windows NT 6.2.9200.0; ; ; 64bit - Extra Info: Enterprise; PIX DRM 1.0.6.0; PIX API 3.7.0.0`

As you can see, there are a lot of versions in there with three dots, not two. Right now I just chop off the end of those versions, but it would be great to handle them.

Any chance of that?

**Comment by eieste** [comment]
Hi

sorry, i didn't get a notification for this issue. 
Unfortunately I can't really help you with this. The project should be 100% compatible with its python version.
 Even if you have already solved it differently, you could fork the repo and create your own version.
